remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Your Project Title
description: A high-level overview of your project
url: "https://cs481-ekh.github.io/s24-gone-phishin/"
baseurl: ""

# Build settings
markdown: kramdown
