name: build

on: 
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        timeout-minutes: 5

        steps:
          - uses: actions/checkout@v4

          - name: Build podman image
            run: podman build -t hooklinesecureimage:0.1 .

          - name: Run build.sh
            run: podman run hooklinesecureimage:01 bash -c "./build.sh"

